### ISSUE TITLE
Access Token Error Bad Request

### ISSUE THREAD

**Issue by haroot** [lelylan/simple-oauth2#141] opened 2017-07-14 20:05 UTC
auth: {
    tokenHost: 'https://www.googleapis.com',
    tokenPath: '/oauth2/v3/token',
    authorizeHost: 'https://accounts.google.com',
    authorizePath: '/o/oauth2/v2/auth',
  },

can you do this? can someone correct this for google and give me a facebook example please?

**Comment by jonathansamines** [comment] 2017-07-19 06:27
Yes, it should be possible. How is this failing for you?. I am not familiar with the facebook oauth system, but should be basically the same as your google setup.

**Comment by haroot** [comment] 2017-07-19 06:46
the "code" comes out good but not the token for facebook google and
(twitter is the worst) only was able to get github to work

On Tue, Jul 18, 2017 at 11:27 PM, Jonathan Samines <notifications@github.com

**Comment by jonathansamines** [comment] 2017-07-25 02:13
@haroot Sorry, but I would need lots of additional information in order to get an idea of what is causing the error. Do you mind to put a reproducible example so I can take a look?

**Comment by haroot** [comment] 2017-07-25 03:01
yah soon I am in a middle of a project and I might have just switched to
passport honestly since the codeflow and routes are better and more logical

**Comment by jonathansamines** [comment] 2017-07-25 16:00
Great, will close this then. Fee free to re-open if you ever found yourself using this library again ;)

**Closed by jonathansamines** 2017-07-25 16:00 UTC

**Comment by benatkin** [comment] 2018-06-12 01:55
Looks like the official google library is duplicating some stuff that this library and express are doing. It would be nice to have a library to glue express and the official google api together. https://github.com/google/google-api-nodejs-client/blob/master/samples/drive/quickstart.js
