### ISSUE TITLE
Potential conflict with latest 1.x version?

### ISSUE THREAD

**Issue by ashic** [lelylan/simple-oauth2#177] opened 2018-03-05 16:40 UTC
We have a project using ^1.3.1. After the latest release, this seems broken for us. With 1.5.1, we're getting:

```
> node ./bin/www
 /usr/src/app/node_modules/simple-oauth2/lib/client/auth-code.js:45
  async function getToken(params) {
        ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/simple-oauth2/index.js:4:24)
    at Module._compile (module.js:541:32)
```

**Comment by pkappe** [comment] 2018-03-05 16:56
I have the same problem. Did a `npm update simple-oauth2 --save` which bumped it to 1.5.1, but now our getToken won't work at all. We were using 1.0.3. Looks like I might have to just use this newer version, or maybe the 2.01 version and move some code around to adapt to the new code. Would be easier not to... but it might not be possible. 

A fix for earlier version would be greatly appreciated.

**Comment by abekim** [comment] 2018-03-05 22:57
I'm also seeing the same errors with the latest updates and I believe this is caused by older Node.js version. According to the compatibility chart, Node.js versions <7.6 will not support the `async function` syntax from ECMA2017. http://node.green/#ES2017-features-async-functions

Having said that, Node6 (Boron) is still considered a supported LTS (long-term-support) version of Node.js (https://github.com/nodejs/Release) until 2019, so I think this update should have been either:
- marked as a breaking change with a major version bump
- or should have been tested for backwards compatibility

Since a major version upgrade for Node.js isn't an option for my project, we'll have to revert the update. A quick resolution to this would be much appreciated!

Best,
Abe

**Comment by jonathansamines** [comment] 2018-03-06 02:57
@abekim @ashic Effectively, v1.5.x is still supported, with commitment to support node 4 and up to node 6 until its EOL.

I just pushed the 1.5.2 version. The 1.5.1 version incorrectly included some breaking changes (was published from the wrong branch). Please let me know if that solves the issue.

**Comment by loslch** [comment] 2018-03-06 05:02
I think this issue might be related to #178 as @jonathansamines mentioned.

**Comment by abekim** [comment] 2018-03-06 13:53
@jonathansamines 1.5.2 addresses the issue; thank you for the speedy followup!

**Closed** 2018-03-06 18:08 UTC
